### ISSUE TITLE
Sticky position issue

### ISSUE THREAD

**Issue by alege** [kimyvgy/simple-scrollspy#38] opened 2023-04-27 14:27 UTC
When some of the `sectionClass` elements have `position: sticky`, `activeClass` is not added to them when scrolling

**Comment by kimyvgy** [comment] 2023-05-25 10:47
Sorry for late response. I will check this issue when having time.

**Comment by jmeile** [comment] 2024-02-25 19:16
Ok, I found the solution. It looks like in my previous solution, it was working sometimes and sometimes not because I had a padding-top on the "h3" element. If I remove that element, then it won't never work.

After some trial and error, I figured out that when working with sticky navigation, I have this conditions:
1. I can't use the scrollIntoView function because it doesn't includes the offsets caused by the top padding, the top margin of the sections and the height of the navigation bar. Instead, I have to use the ScrollTo function, which allows me to specify the new computed left and top coordinates of the section.
2. The top padding and the top margin must be always subtracted when working with sticky elements.
3. The height, top, and bottom padding of the navigation bar also needs to be subtracted, but only if it is not sticked.
4. Finally, you should not add any kind of top padding or top margin to the section titles; otherwise, the results won't be as you want them to be. The elements will appear with a different vertical offset.  So, it is better if you leave the top padding and top margin for the section elements directly.

There is still a little pixel offset on my solution, but I guess I still can add 4 pixels more and it will be fixed:
https://fiddle.jshell.net/jmeile/w9b6fc8n/242

**Comment by kimyvgy** [comment] 2024-09-19 03:47
This issue has been closed due to prolonged inactivity.

**Closed by kimyvgy** 2024-09-19 03:47 UTC
